version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=bpu55jwtnjsibxgvi6pp-mysql.services.clever-cloud.com
      - DB_DATABASE=bpu55jwtnjsibxgvi6pp
      - DB_USERNAME=uykcylzrbuhhofr3
      - DB_PASSWORD=uVpNdeOFAa60nLdhJBQ2